### ISSUE TITLE
Perl =~ /REGEX/ parsing error (match operator)

### ISSUE THREAD

**Issue by mabstorm** [klorenz/atom-regex-railroad-diagrams#15]
Given this test in perl:
$line =~ /[a-z]*/

Or any test of the form:
$variablename =~ /REGEX/

This error pops up:
~ /[a-z]*/
   ^
Expected "$", "("...........CharacterSet, Literal, or Quantifier but "/" found (for the first "/")

"MATCH operators will test a string of information to see if the specified regular expression is present. If true, the statement returns a true (non-zero) value. If no match, it returns a zero or false value. The match is symbolized by an equals and tilde. "

Do you think there's anything you can do about this?
(PS. This tool is awesome when it works!)

**Comment by klorenz** [comment]
This issue is not present anymore.
