### ISSUE TITLE
PHP regex delimiters throw errors

### ISSUE THREAD

**Issue by valorin** [klorenz/atom-regex-railroad-diagrams#16]
PHP uses delimiters around a regex string, see: http://php.net/manual/en/regexp.reference.delimiters.php . However, this confuses this plugin completely. For example, this is a valid regex in PHP:

```
preg_match("/^abc[def]g/",$target)
```

But it throws this error:

```
"/^abc[def]g/"
 ^
 Expected "$", "(", ".", "\\", "\\0", "\\A", "\\B", "\\D", "\\G", "\\S", "\\W", "\\Z", "\\b", "\\c", "\\d", "\\f", "\\n", "\\r", "\\s", "\\t", "\\u", "\\v", "\\w", "\\x", "\\z", "|", CharacterSet, Literal or Quantifier but "/" found.
```

Is there any way to check for .php files and handle the delimiter automatically?

**Comment by klorenz** [comment]
this is fixed.
