### ISSUE TITLE
Ruby expressions in %r{} error.

### ISSUE THREAD

**Issue by mrinalwadhwa** [klorenz/atom-regex-railroad-diagrams#18]
This renders the diagram properly: `/^\/folder\/.+\// =~ "/folder/test/"`

But this: `%r{^\/folder\/.+\/} =~ /folder/test/`
Throws the following error:

![error](https://cloud.githubusercontent.com/assets/159583/3716717/ff594d30-1614-11e4-822b-9a43c426bfae.jpg)

**Comment by ypresto** [comment]
:+1:
