### ISSUE TITLE
Doesn't support / in a coffeescript heregex

### ISSUE THREAD

**Issue by kmdavis** [klorenz/atom-regex-railroad-diagrams#26]
If you have a heregex (a coffeescript feature that combines a heredoc with a regex) like `///asdf/1234///g` it will choke on the embedded /

![screen shot 2015-01-21 at 4 29 28 pm](https://cloud.githubusercontent.com/assets/132806/5845536/b675185e-a18a-11e4-851c-7dc8f81c32b8.png)

**Comment by lordjavac** [comment]
This is also true in other languages where you can use different surrounding delimiters for your regexes, e.g. Ruby's %r{} syntax (or perl).

Looking into it a little deeper. Ruby, at least, defines punctuation.section.regexp.begin (and corresponding end). If these scopes are in the string.regex scope, they should be removed and treat the rest as the content of the reggae, allowing slashes if the punctuation was not slashes.

**Comment by klorenz** [comment]
@lordjavac ty for the syntax scope hint, I will make use of this.

**Comment by klorenz** [comment]
done.
