### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by d4k0** [klorenz/atom-regex-railroad-diagrams#37]
Since the update to Atom 0.189.0, this message appears:

Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `regex-railroad-diagram` package
```
Package.getStylesheetsPath (D:\Programme\Dokumente\Atom\resources\app\src\package.js:448:9)
Package.getStylesheetPaths (D:\Programme\Dokumente\Atom\resources\app\src\package.js:459:32)
```

The fix should be simple: You only have to rename the folder ```stylesheets``` to ```styles```. You also have to adjust the path if you used the original path in your code (I found one case in the file ```select-list-view.js``` at line 12).

**Comment by ilanbiala** [comment]
@klorenz Still an issue, please fix this.

**Comment by optikfluffel** [comment]
> On June 1st all deprecated APIs in Atom will be removed in preparation for the 1.0 Atom release later that month.

from [blog.atom.io/2015/05/01/removing-deprecated-apis.html](http://blog.atom.io/2015/05/01/removing-deprecated-apis.html)

**Comment by ilanbiala** [comment]
@klorenz please fix this.

**Comment by kyoh86** [comment]
@klorenz Plz..

**Comment by JacopoGobbi** [comment]
@klorenz Please, your package is very useful!

**Comment by iamstarkov** [comment]
@klorenz are patches welcomed?

**Comment by optikfluffel** [comment]
@iamstarkov a PR is already open at #39

**Comment by ilanbiala** [comment]
@klorenz still waiting on #39 to be merged in.
