### ISSUE TITLE
Does not show view on Atom 0.202.0

### ISSUE THREAD

**Issue by ypresto** [klorenz/atom-regex-railroad-diagrams#42]
It does not show diagram view even when regex is under the cursor.
Command palette does not show shortcut for toggling diagram too.

### How to reproduce

1. Install/update to Atom 0.202.0
1. mv ~/.atom ~/.____atom # emulate clean install
1. apm install regex-railroad-diagram
1. atom
1. Open coffeescript file
1. Move cursor to regex
1. Nothing happen

**Comment by ypresto** [comment]
It seems to be problem in atom.

```
editor.bufferRangeForScopeAtCursor('.string.regexp')
Range {start: Point, end: Point, copy: function, negate: function, serialize: function…}
editor.bufferRangeForScopeAtCursor('.regexp')
undefined
```

**Comment by ypresto** [comment]
It was destructive change on experimental api.

**Comment by klorenz** [comment]
I close this issue, it is outdated. (atom > 1.0)
