### ISSUE TITLE
Is this still maintained, do we need a fork?

### ISSUE THREAD

**Issue by Bertg** [klorenz/atom-regex-railroad-diagrams#45]
Hi all,

I really love this package, both as a tool, but also to teach regular expressions to people. To bad it doesn't seem to be maintained anymore.

Is there any news from @klorenz on the commitment for this package? Does anyone who has already created PR"s or personal forks feel like creating a forked release?
Is there anything else that could be done?

**Comment by suda** [comment]
:+1:

**Comment by petey** [comment]
:+1:

**Comment by Nicolab** [comment]
:+1

**Comment by klorenz** [comment]
Hi all
sorry I was pretty busy in the last months.  I am preparing a new package with many fixes right now.
Regards, Kiwi

**Comment by Bertg** [comment]
Hurray!

**Comment by Nicolab** [comment]
Great, thanks!
