### ISSUE TITLE
Balks on ^ in certain situations

### ISSUE THREAD

**Issue by gilbox** [klorenz/atom-regex-railroad-diagrams#51]
First of all, really cool plugin. Thanks!

I noticed this fails:

      var a =  /^foo/;

... it complains about the `^`

![image](https://cloud.githubusercontent.com/assets/2136203/8556883/7734c816-24bf-11e5-9cb6-0919f316ed1b.png)

but this works:

      var a =  (/^foo/);

and so does this:

      /^foo/

**Comment by petey** [comment]
I'm hitting this now too.

**Comment by biji** [comment]
also happen in PHP source:

            if (! preg_match('/^[RK]_.{16}\.pdf$/', $name)) {

![regex](https://cloud.githubusercontent.com/assets/665559/9610044/40287ea8-5101-11e5-9bcd-aef123358243.png)

**Comment by klorenz** [comment]
fixed in 0.9.1
