### ISSUE TITLE
Suggestion: escaped charaters should not be shown separately from other character literals

### ISSUE THREAD

**Issue by aharpervc** [klorenz/atom-regex-railroad-diagrams#54]
For example: `/dbo\.Test\(\)/` should show up as a single bubble, `dbo.Test()` rather than 5: `dbo` `.` `Test` `(` `)`. I suppose this could also live as a new option, "coalesce escaped literals with adjacent literals" or something.

**Comment by klorenz** [comment]
Done in 0.9
