### ISSUE TITLE
Problem understanding end of regex

### ISSUE THREAD

**Issue by aharpervc** [klorenz/atom-regex-railroad-diagrams#59]
This is 0.91, in a .rb file:

    matches = /Invalid column name '(?<identifier>.*?)'/.match error_text

![ss1](http://i.imgur.com/mPNXeZd.png)

That line starts with 3 tabs. When I bump it up to 5 tabs, I get this:

![ss2](http://i.imgur.com/1Rbz55s.png)

**Comment by aharpervc** [comment]
Possibly related to #58

**Comment by klorenz** [comment]
fixed (with workaround) in 0.10.0
