### ISSUE TITLE
Make closeable or resizeable

### ISSUE THREAD

**Issue by BlaM** [klorenz/atom-regex-railroad-diagrams#61]
The "railroad" track should have some kind of close functionality (ESC?) because some regular expressions may eat up all screen estate. Right now I have a regex on screen that leaves me 10 lines of code visible on the screen. Not much more needed and I can't see my code at all. ;)

**Comment by klorenz** [comment]
you now can disable/enable the diagram (0.14.0) and maximum height is half of view height.  does this fix this issue for you? (It is not yet resizable)

**Comment by BlaM** [comment]
I will test later, but it sounds great. Thank you  :+1:
