### ISSUE TITLE
Overlaps preview

### ISSUE THREAD

**Issue by rugk** [klorenz/atom-regex-railroad-diagrams#65]
As at least in my small test my regexp did not had a big width, but rather a big height I do not need the full screen width for displaying them.
However this is what this extension currently does. So IMO if a (HTML/markdown/...) preview is opened you should not overlap it, but better end there. If the RegExp is longer you may obviously scroll.

But as I assume some people do not like this I would say this should be made configurable, so you can easily deactivate it.

**Comment by klorenz** [comment]
fixed
