### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by stugol** [klorenz/atom-regex-railroad-diagrams#69]
Wow! This is really useful, thanks!

You mention it's not fully-featured yet. Which regex features does it _not_ support? Lookahead maybe? How long until it's fully complete?

**Comment by klorenz** [comment]
Hi Stugol,

there are some special features about perl regexes like code extension, some Oniguruma escapes and some other things not supported.  Lookahead and lookbehind, negative and positive are supported.

When I wrote this, also inline mode changes like (?i) were not supported, but now are, so were not named captures.

If you find features, which should be supported, please tell me.

Cheers :)
