### ISSUE TITLE
Check strings for escaped regex

### ISSUE THREAD

**Issue by baelter** [klorenz/atom-regex-railroad-diagrams#70]
Would be nice if strings where unescaped and checked for regex type.

e.g. regex in json string.

**Comment by klorenz** [comment]
Hi Anders,

I do not know exactly what you mean.  JSON does not know regexes.  Do you think
of syntax highlight descriptions?  If so, please take a look at another package
of mine, which you can use for writing coffeescript or javascript and generate
the syntax theme from it: https://www.npmjs.com/package/atom-syntax-tools

Best regards, Kiwi


Am 22.04.2016 um 20:26 schrieb Anders Bälter:

**Comment by baelter** [comment]
```json
{
  "var" : "^.*\\d+§"
}
```

escaped regex in strings like this.

**Comment by edgerunner** [comment]
I think there would be a lot of cases where a regex in a string would be very hard to tell apart from a regular string, and vice versa. 

A better solution may be the ability to invoke the diagram manually (via a keyboard shortcut or menu command) in which case it could evaluate a string literal as regex.

**Comment by baelter** [comment]
Agree
