### ISSUE TITLE
What languages does this support?

### ISSUE THREAD

**Issue by Dangthrimble** [klorenz/atom-regex-railroad-diagrams#74]
I've installed the package, opened files with regex in them and created new buffers and typed regex into them but no railroad diagrams appear. I've even restarted Atom to no avail. Does this only work for certain languages? Can the display be toggled? Or am I missing something more fundamental?

Thanks

**Comment by klorenz** [comment]
Hi Dangthrimbie,

basically it supports all languages, which have atom syntax-highlighting and mark its regular expressions in a reasonable way.  But there are some special treatments for languages like python, 
ruby, etc.

The display toggles automatically as soon your cursor in on a regex.

Which language do you miss?

Best regards, Kiwi

**Comment by SolomonShorser-OICR** [comment]
I often have regular expressions quoted as strings to pass on to some other function, and the plugin doesn't seem to be able to handle those, for example (in perl): `$rnd->randregex('\w{16}');`

Would it be possible to have a feature that the user can manually trigger when a regex string is highlighted by the user?

**Comment by PurpleMagick** [comment]
I was wondering why I couldn't get this extension to work. All of our codebase is using tab characters instead of spaces. When I saw this issue, I tried converting one file to spaces and the extension immediately worked. Then JSCS immediately threw a fit.

**Comment by klorenz** [comment]
Hi all, I implemented @dflocks feature request, which should fix the initial request.
@PurpleMagick, I also removed a former workaround, which calculated with tabs and spaces, so maybe your issue is also fixed.
