### ISSUE TITLE
My cursor stop and click the current ``regex`` line,But no  graphic reflection

### ISSUE THREAD

**Issue by hebijiandai** [klorenz/atom-regex-railroad-diagrams#82]
```python
import re
import requests
from pprint import pprint

url = "https://kyfw.12306.cn/otn/resources/js/framework/station_name.js?station_version=1.8983"
response = requests.get(url, verify=False)
stations = re.findall(u'([\u4e00-\u9fa5]+)\|([A-Z]+)', response.text)
pprint(dict(stations), indent=4)
```
![qq 20161213125557](https://cloud.githubusercontent.com/assets/5127081/21128149/866f4966-c133-11e6-96a0-52ba4719d1bc.png)

Hello sir,My cursor stop and click the current ``regex`` line,But no  graphic reflection

I have enable the package.

How to solve this?Many thanks.

**Comment by klorenz** [comment]
@hegijindai, in python language atom only recognizes r"" strings as regular expressions.  Unicode strings are treated as normal strings.  in this case (in your code) simple replacing the u with an r should do it (and code should still work).  Apart from this there is a new feature, that you can select text and hit ctrl-r ctrl-r for displaying the railroad diagram
