### ISSUE TITLE
support for more complicated regex expression like email verification

### ISSUE THREAD

**Issue by wangbourne** [klorenz/atom-regex-railroad-diagrams#89]
it does not work this kind of expression (email verification)

var re = /^(([^<>()[].,;:s@"]+(.[^<>()[].,;:s@"]+)*)|(".+"))@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}])|(([a-zA-Z-0-9]+.)+[a-zA-Z]{2,}))$/

**Comment by mikesprague** [comment]
Seems to be working fine. I would suspect at least one of the following:

1. The plugin is installed but not enabled
2. Your cursor isn't currently inside the regex
3. You don't have a "grammar" selected (e.g. it's set to JavaScript in my screenshot)

![atom-regex-railroad-issue-89](https://cloud.githubusercontent.com/assets/560705/25782551/3ce15f6e-331b-11e7-93df-102979a3bd9b.png)
